#!/usr/bin/env node
/**
 * 夜が赤いことを**台帳に出す**(#221、2026-08-17)。
 *
 * 🔴 直すまで、Nightly は **2026-08-04 から 13 晩**赤かったのに誰も気づかなかった。
 * PR gate は緑なので、**こちらの計器は 1 つも鳴らない** ── 気づく導線が
 * 「たまたま Actions を開く」しか無かったのが原因である。
 *
 * 🔑 **やることは issue に置く**(user 指示 2026-08-15「ファイルをただ置いておくのは
 * やめろ」)。だから赤くなったら issue を 1 本立て、赤い間はそこへ積み、
 * **緑に戻ったら閉じる**。⚠ 夜ごとに新しい issue を立てない(台帳が埋まる)。
 *
 *   PKC3_NIGHTLY_FAILED="Probe — sidebar,Probe — editor" node scripts/nightly-red.mjs
 *   PKC3_NIGHTLY_FAILED=""                                node scripts/nightly-red.mjs  # 緑
 *
 * ⚠ 規則の本体(どの API をどう叩くか)は `reconcileNightlyIssue` に閉じてあり、
 *   `tests/nightly-red.test.ts` が偽の `fetch` で全 4 経路を走らせる ──
 *   「どの test からも実行されない file に判断を書かない」(CLAUDE.md §2)。
 */
import { fileURLToPath } from 'node:url';

/** 赤い夜を束ねる 1 本の issue を指す印。 */
export const LABEL = 'nightly-red';

const API = 'https://api.github.com';

/**
 * 夜の結果に合わせて issue を 1 本だけ保つ。
 *
 * @param {object} o
 * @param {typeof globalThis.fetch} o.fetch
 * @param {string} o.repo   `owner/name`
 * @param {string} o.token
 * @param {string[]} o.failedSteps 落ちた step 名(空 = 緑)
 * @param {string} o.runUrl この run の URL
 * @param {string} o.today  `2026-08-17`(件名に入れる)
 * @returns {Promise<{action: 'created'|'commented'|'closed'|'noop', issue: number|null}>}
 */
export async function reconcileNightlyIssue({ fetch, repo, token, failedSteps, runUrl, today }) {
  const red = failedSteps.length > 0;
  const call = async (method, path, body) => {
    const res = await fetch(`${API}${path}`, {
      method,
      headers: {
        accept: 'application/vnd.github+json',
        authorization: `Bearer ${token}`,
        'content-type': 'application/json',
        'x-github-api-version': '2022-11-28',
      },
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    });
    // ⚠ 落ちたら**黙って続けない** ── 通知が届かないことこそ、この script が
    //   直そうとしている症状である(例外は step を赤くする)
    if (!res.ok) throw new Error(`${method} ${path} → ${res.status}`);
    return res.json();
  };

  const list = await call(
    'GET',
    `/repos/${repo}/issues?state=open&labels=${encodeURIComponent(LABEL)}&per_page=10`,
  );
  // ⚠ issues API は **PR も返す** ── 混ざると PR にコメントし始める
  const openIssue = (Array.isArray(list) ? list : []).find((i) => !i.pull_request) ?? null;

  if (!red) {
    if (!openIssue) return { action: 'noop', issue: null };
    await call('POST', `/repos/${repo}/issues/${openIssue.number}/comments`, {
      body: `✅ 夜が緑に戻りました(${today})。\n\n${runUrl}\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_`,
    });
    await call('PATCH', `/repos/${repo}/issues/${openIssue.number}`, {
      state: 'closed',
      state_reason: 'completed',
    });
    return { action: 'closed', issue: openIssue.number };
  }

  const steps = failedSteps.map((s) => `- ${s}`).join('\n');
  if (openIssue) {
    await call('POST', `/repos/${repo}/issues/${openIssue.number}/comments`, {
      body: `🔴 ${today} も赤でした。\n\n落ちた step:\n${steps}\n\n${runUrl}\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_`,
    });
    return { action: 'commented', issue: openIssue.number };
  }

  // ⚠ label が無い repo で issue 作成ごと落ちないように、先に作っておく
  //   (既に在れば 422。**それは失敗ではない**)
  const res = await fetch(`${API}/repos/${repo}/labels`, {
    method: 'POST',
    headers: {
      accept: 'application/vnd.github+json',
      authorization: `Bearer ${token}`,
      'content-type': 'application/json',
      'x-github-api-version': '2022-11-28',
    },
    body: JSON.stringify({ name: LABEL, color: 'b60205', description: '夜の検査が赤い' }),
  });
  if (!res.ok && res.status !== 422) throw new Error(`POST /labels → ${res.status}`);

  const created = await call('POST', `/repos/${repo}/issues`, {
    title: `🔴 Nightly が赤い(${today} 〜)`,
    labels: [LABEL],
    body:
      `${today} の Nightly が赤くなりました。**緑に戻るまでこの issue へ積まれます**` +
      `(戻ったら自動で閉じます)。\n\n落ちた step:\n${steps}\n\n${runUrl}\n\n` +
      `⚠ 夜の検査は **1 つ落ちても後続を止めません**(#221)。落ちた step が複数なら、` +
      `それぞれ別の主張が壊れています。\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_`,
  });
  return { action: 'created', issue: created.number };
}

/* ── CLI ── */
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const repo = process.env.GITHUB_REPOSITORY;
  const token = process.env.GITHUB_TOKEN;
  const runId = process.env.GITHUB_RUN_ID;
  const server = process.env.GITHUB_SERVER_URL ?? 'https://github.com';
  if (!repo || !token) {
    console.error('✗ GITHUB_REPOSITORY / GITHUB_TOKEN が要る');
    process.exit(2);
  }
  const failedSteps = (process.env.PKC3_NIGHTLY_FAILED ?? '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
  const today = new Date().toISOString().slice(0, 10);
  const out = await reconcileNightlyIssue({
    fetch: globalThis.fetch,
    repo,
    token,
    failedSteps,
    runUrl: `${server}/${repo}/actions/runs/${runId}`,
    today,
  });
  console.log(`${out.action}${out.issue ? ` #${out.issue}` : ''}`);
}
